title: Violet
descriptionX: Sophisticated Conversational Apps on Amazon's Alexa
description: Enabling Sophisticated Voice Conversations
github:
  repository_url: https://github.com/salesforce/violet-conversations
  zip_url: http://github.com/salesforce/violet-conversations/zipball/master
  tar_url: http://github.com/salesforce/violet-conversations/tarball/master
google_analytics: UA-109193428-1
