title: HelloViolet.ai - Voice Application Framework
description: Enabling Sophisticated Voice Conversations
google_analytics: UA-109193428-1
release_version: v0.7.0
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-feed
