theme: jekyll-theme-slate
title: Violet
descriptionX: Sophisticated Conversational Apps on Amazon's Alexa
description: Enabling Sophisticated Voice Conversations
github:
  repository_url: https://github.com/salesforce/violet-conversations
google_analytics: UA-109193428-1
